Marcomm.Web/Controllers/CompanyController.cs
using Marcomm.DAL;
using Marcomm.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marcomm.Web.Controllers
{
    public class CompanyController : Controller
    {
        // GET: Company
        public ActionResult Index()
        {
            ViewBag.ListCompanyCode = new SelectList(CompanyDAL.Get(), "code", "code");
            ViewBag.ListCompanyName = new SelectList(CompanyDAL.Get(), "name", "name");
            return View(CompanyDAL.Get());
        }

        public ActionResult List()
        {
            return PartialView(CompanyDAL.Get());
        }

        public ActionResult Add()
        {
            var data = new CompanyViewModel();
            data.code = CompanyDAL.KodeAuto();
            return PartialView(data);
        }

        [HttpPost]
        public ActionResult Add(CompanyViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (CompanyDAL.Cek(model.name, model.id) == true)
                {
                    if (CompanyDAL.Insert(model) == true)
                    {
                        var result = new
                        {
                            success = true,
                            alertType = "info",
                            alertStrong = "Data Saved!",
                            alertMessage = "New Company has been add with code " + model.code
                        };
                        return Json(result, JsonRequestBehavior.AllowGet);
                    }
                }
                else if (CompanyDAL.Cek(model.name, model.id) == false)
                {
                    var result = new { success = false };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView();
        }

        public ActionResult Edit(int id)
        {
            return PartialView(CompanyDAL.Get(id));
        }

        [HttpPost]
        public ActionResult Edit(CompanyViewModel model)
        {
            //if (ModelState.IsValid)
            {
                if (CompanyDAL.Cek(model.name, model.id) == true)
                {
                    if (CompanyDAL.Update(model) == true)
                    {
                        var result = new 
                        { 
                            success = true, 
                            alertType="info",
                            alertStrong="Data Updated!",
                            alertMessage="New Company has been updated!"
                        };
                        return Json(result, JsonRequestBehavior.AllowGet);
                    }
                }
                else if (CompanyDAL.Cek(model.name, model.id)==false)
                {
                    var result = new { success = false };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView(model);
        }

        public ActionResult Delete(int id)
        {
            var data = CompanyDAL.Get(id);
            CompanyDAL.Delete(id);
            var result = new
            {
                success = true
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public ActionResult Delete(CompanyViewModel model)
        //{
        //    if (CompanyDAL.Delete(model))
        //    {
        //        var result = new { success = true, message = "Success" };
        //        return Json(result, JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        var result = new { success = false, message = "Failed" };
        //        return Json(result, JsonRequestBehavior.AllowGet);
        //    }
        //    return PartialView();
        //}

        public ActionResult Detail(int id)
        {
            return PartialView(CompanyDAL.Get(id));
        }

        public ActionResult panggil(int id)
        {
            var result = new
            {
                success = true,
                data = CompanyDAL.Get(id)
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Marcomm.Web/Views/Company/Add.cshtml
@model Marcomm.ViewModel.CompanyViewModel
@{
    ViewBag.Title = "Add";
}

@using (Html.BeginForm("Add", "Company", FormMethod.Post, new { @id="form"}))
{
    @Html.HiddenFor(x => x.isDelete, new { Value = false })
    @Html.HiddenFor(x => x.createdBy, new { Value = "Admin" })
    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.code, htmlAttributes: new { @class="control-label col-md-4"})
                <div class="col-md-8">
                        @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = "true" })
                        @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })
                    
                </div>
            </div>
            

            <div class="form-group">
                @Html.LabelFor(x => x.email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.email, null, new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.phone, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.phone, null, new { @class = "text-danger" })

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.address, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.address, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>
        


        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
                <a id="btn-cancel" class="btn btn-warning btn-sm">Cancel</a>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Company/Delete.cshtml
@model Marcomm.ViewModel.CompanyViewModel
@{
    ViewBag.Title = "Delete";
}
<table>
    <tr>
        <td width="3">
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(x => x.id)
                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            }
        </td>
        <td>
            <button id="btn-cancel" class="btn btn-warning btn-sm">Cancel</button>
        </td>
    </tr>
</table>

Marcomm.Web/Views/Company/Detail.cshtml
@model Marcomm.ViewModel.CompanyViewModel
@{
    ViewBag.Title = "Detail";
}
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.isDelete, new { Value = false })
    @Html.HiddenFor(x => x.createdBy, new { Value = "Admin" })
    @Html.HiddenFor(x => x.id)
    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.code, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.email, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.email, null, new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.phone, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.phone, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.phone, null, new { @class = "text-danger" })

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.name, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.address, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.address, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.address, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <a id="btn-cancel" class="btn btn-warning btn-sm">Close</a>
            </div>
        </div>
    </div>
}

Marcomm.Web/Views/Company/Edit.cshtml
@model Marcomm.ViewModel.CompanyViewModel
@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.isDelete, new { Value = false })
    @Html.HiddenFor(x => x.createdBy, new { Value = "Admin" })
    @Html.HiddenFor(x => x.id)
    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.code, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })

                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.email, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.email, null, new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.phone, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.phone, null, new { @class = "text-danger" })

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.address, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.address, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
                <a id="btn-cancel" class="btn btn-warning btn-sm">Cancel</a>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Company/Index.cshtml
@model IEnumerable<Marcomm.ViewModel.CompanyViewModel>
@{
    ViewBag.Title = "Index";
}

<div class="box box-primary box-solid">
    <div class="box-header">
        <div class="box-title">List Company</div>
    </div>

    <div class="box-body">
        <ol class="breadcrumb">
            <li>Home</li>
            <li>Master</li>
            <li>List Company</li>
        </ol>

        <table class="table table-bordered table-responsive table-striped" id="list-role">
            <thead id="tb-input">
                <tr>
                    <td colspan="5"></td>
                    <td>
                        <button type="button" class="btn btn-primary col-md-7" id="btn-add">Add</button>
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td>@Html.DropDownList("code", (IEnumerable<SelectListItem>)ViewBag.ListCompanyCode, "- Select Company Code -", new { @class = "form-control column-filter", @id = "col1_filter", @data = "1" })</td>
                    <td>@Html.DropDownList("name", (IEnumerable<SelectListItem>)ViewBag.ListCompanyName, "- Select Company Name -", new { @class = "form-control column-filter", @id = "col2_filter", @data = "2" })</td>
                    <td>
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="datepicker form-control column_filter" id="col3_filter" data="3" placeholder="Created" />
                        </div>
                    </td>
                    <td>@Html.TextBox("createdBy", "", new { @class = "form-control column-filter", @id = "col4_filter", @data = "4", @placeholder = "Created By" })</td>
                    <td>
                        <button type="button" class="btn btn-warning" id="btn-src">Search</button>
                    </td>
                </tr>
                <tr>
                    <th>No.</th>
                    <th>@Html.DisplayNameFor(x => x.code)</th>
                    <th>@Html.DisplayNameFor(x => x.name)</th>
                    <th>@Html.DisplayNameFor(x => x.createdDate)</th>
                    <th>@Html.DisplayNameFor(x => x.createdBy)</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="list-data">
                @Html.Partial("List", Model)
            </tbody>
        </table>
    </div>
</div>




<div class="modal fade" id="modal-input">
    <div class="modal-dialog" role="dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">Modal Header</h3>
            </div>
            <div class="modal-body" id="modal-body">

            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        function loadData() {
            $.ajax({
                url: "@Url.Action("List","Company")",
                type: "get",
                dataType: "html",
                success: function (x) {
                    $("#list-data").html(x);
                }
            });
        };

        $(document).ready(function () {
            $("#list-role").DataTable({
                'sDom': 'tip',
                ordering: false
            });
            $("#tb-input").find(".column_filter").on("keyup click", function () {
                filtercolumn($(this).attr("data-column"));
            });
        });

        function filtercolumn(i) {
            $("#list-role").DataTable().column(i).search(
                $("#col" + i + "_filter").val()
                ).draw();
        };

        //script button search
        $("#btn-src").click(function () {
            $("#tb-input .form-control").each(function () {
                filtercolumn($(this).attr('data'));
            });
        });

        $("#tb-input").find(".datepicker").datepicker({
            Format: "MM/dd/yyyy",
            autoclose: true
        });
        //ADD Get, menampilkan Add di dalam modal-input
        $("#btn-add").click(function () {
            $.ajax({
                url: "@Url.Action("Add", "Company")",
                type: "get",
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Add Company");
                    $("#modal-input").modal('show');
                }
            });
        });

        //untuk cancel
        $("#modal-input").on("click", "#btn-cancel", function () {
            $("#modal-input").modal('hide');
        });

        //Untuk submit data melalui form Add, action Add
        $("#modal-input").on("submit", "form", function () {
            var dataURL = $(this).attr("action");
            var dataMethod = $(this).attr("method");
            var dataItem = $(this).serialize();

            $.ajax({
                url: dataURL,
                type: dataMethod,
                data: dataItem,
                dataType: "json",
                success: function (hasil) {
                    if (hasil.success==true) {
                        loadData();
                        $("#modal-input").modal('hide');
                        var response = '<div class="alert alert-' + hasil.alertType + ' alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>' + hasil.alertStrong + '</strong> ' + hasil.alertMessage + '.</div>';
                        $('#AlertResponse').hide().html(response).fadeIn(1500);
                        $('.alert').delay(5000).fadeOut('normal', function () {
                            $(this).remove();
                        });
                    } else if (hasil.success==false) {
                        swal({
                            title: 'Data has been created',
                            animation: true,
                            customClass: 'animated tada'
                        })
                    }
                }
            });
            return false;
        });

        //Edit data
        $("#list-data").on("click", "#btn-edit", function () {
            var dataId = $(this).val();
            $.ajax({
                url: "@Url.Action("panggil")",
                type: "get",
                data: { id: dataId },
                dataType: "json",
                success: function (hasil) {
                    if(hasil.success==true){
                        var nama=hasil.data.name;
                        var code=hasil.data.code;
                        $.ajax({
                            url: "@Url.Action("Edit")",
                            type: "get",
                            data: { id: dataId },
                            dataType: "html",
                            success: function(hasil){
                                $("#modal-body").html(hasil);
                                $("#modal-title").html("Edit User " + nama + " (" + code + " )");
                                $("#modal-input").modal('show');
                            }
                        })
                    }
                }
            });
        });

        //Hapus data
        @*$("#list-data").on("click", "#btn-delete", function () {
            var dataId = $(this).val();

            $.ajax({
                url: "@Url.Action("Delete", "Company")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Delete Data?");
                    $("#modal-input").modal('show');
                }
            });
        });*@

        $("#list-data").on("click", "#btn-delete", function()
        {
            var id = $(this).val();
            $.ajax({
                url: "@Url.Action("panggil")",
                type: "get",
                dataType: "json",
                data: { id: id },
                success: function (x) {
                    swal({
                        title: 'Delete ' + x.data.name + ' ( ' + x.data.code + ' )?',
                        text: "Are you sure?",
                        type: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: 'Yes delete it!',
                        cancelButtonColor: 'cancel!',
                        reverseButtons: true
                    }).then((result) => {

                        if (result.value) {
                            $.ajax({
                        url: '/Company/Delete/' + id,
                    type: "get",
                    dataType: "json",
                    success: function (x) {
                        if (x.success == true) {
                            swal(
                                'Data Deleted!',
                                'Data company has been deleted!',
                                'success'
                                );
                        }
                        loadData();
                    }
                });
        }
        else if (result.dismiss === swal.DismissReason.cancel) {
            swal (
                'Canceled',
                'Your imaginary file is safe',
                'warning'
                );
        }
        })
        }
        });
        });

        //data detail
        $("#list-data").on("click", "#btn-view", function () {
            var dataId = $(this).val();
            $.ajax({
                url: "@Url.Action("Detail", "Company")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Data Detail");
                    $("#modal-input").modal('show');
                }
            });
        });
    </script>
}

Marcomm.Web/Views/Company/List.cshtml
@model IEnumerable<Marcomm.ViewModel.CompanyViewModel>
@{
    ViewBag.Title = "List";
    int i = 0;
}
@foreach (var item in Model)
{
    i += 1;
    <tr>
        <td>@i</td>
        <td>@item.code</td>
        <td>@item.name</td>
        <td>@item.createdDate</td>
        <td>@item.createdBy</td>
        <td>
            <button class="btn btn-success btn-xs" id="btn-view" value="@item.id">
                <i class="glyphicon glyphicon-eye-open"></i>
            </button>

            <button class="btn btn-warning btn-xs" id="btn-edit" value="@item.id">
                <i class="glyphicon glyphicon-pencil"></i>
            </button>

            <button class="btn btn-danger btn-xs" id="btn-delete" value="@item.id">
                <i class="glyphicon glyphicon-trash"></i>
            </button>
        </td>
    </tr>
}