Marcomm.Web/Controllers/UnitController.cs
using Marcomm.ViewModel;
using Marcomm.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Marcommm.DAL;

namespace Marcomm.Web.Controllers
{
    [Authorize]
    public class UnitController : Controller
    {
        public ActionResult Index()
        {
            return View(UnitDAL.Get());
        }

        public ActionResult List()
        {
            return PartialView(UnitDAL.Get());
        }

        /*[HttpPost]
        public ActionResult Search(UnitViewModel model)
        {
            return View("Index",UnitDAL.Get(model));
        }*/

        public ActionResult Add()
        {
            UnitViewModel Unit = new UnitViewModel();
            Unit.code = UnitDAL.getCode();

            return PartialView(Unit);
        }

        [HttpPost]
        public ActionResult Add(UnitViewModel model)
        {
            if (UnitDAL.cek(model.name) == false)
            {
                var User = (Marcomm.ViewModel.UserViewModel)Session["User"];
                model.isDelete = false;
                model.createdDate = DateTime.Now.Date;
                model.createdBy = User.mRoleName;
                if (ModelState.IsValid)
                {
                    if (UnitDAL.Insert(model))
                    {
                        var result = new { success = true, message = "Data Berhasil Tersimpan", code = model.code, from = "add" };
                        return Json(result, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var result = new { success = false, message = "Data Gagal Tersimpan" };
                        return Json(result, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            else
            {
                if (UnitDAL.cekAda(model.name) == true)
                {
                    var result = new { success = "ada", message = "Data sudah ada!", name = model.name };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    UnitDAL.UpdateAda(model);
                    var result = new { success = "kembali", name = model.name };
                    return Json(result, JsonRequestBehavior.AllowGet);

                }
            }
            return PartialView(model);
        }

        public ActionResult Edit(int id)
        {
            return PartialView(UnitDAL.Get(id));
        }

        [HttpPost]
        public ActionResult Edit(RoleViewModel model)
        {
            var User = (Marcomm.ViewModel.UserViewModel)Session["User"];
            model.updateBy = User.mRoleName;
            if (RoleDAL.Update(model))
            {
                var result = new { success = true, message = "Data Berhasil diubah", code = model.code, from = "edit" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { success = false, message = "Data Gagal diubah" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView();
        }

        public ActionResult Delete(int id)
        {
            return PartialView(UnitDAL.Get(id));
        }

        [HttpPost]
        public ActionResult Delete(UnitViewModel model)
        {
            if (UnitDAL.Delete(model))
            {
                var result = new { success = true, message = "Data Berhasil Dihapus", from = "delete", code = model.code };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { success = false, message = "Data Gagal Dihapus" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            return PartialView();
        }

        public ActionResult Details(int id)
        {
            return PartialView(UnitDAL.Get(id));
        }
    }
}

Marcomm.Web/Views/Unit/Add.cshtml
@model Marcomm.ViewModel.UnitViewModel
@{
    ViewBag.Title = "Add";
}
@using (Html.BeginForm())
{
    //<input value=@Session["role"] type="hidden" name="createdBy" />
    <input value="Admin" type="hidden" name="createdBy" />
    <div class="box box-primary box-solid">
        <div class="box-header">
            <div class="box-title"><strong>Add Unit</strong></div>
        </div>
        <div class="box-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.Label("*Unit Code")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = true, id = "code" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.Label("*Unit Name")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.name, new { @class = "form-control", id = "name", @onFocusOut = "coba()" })
                        @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.LabelFor(x => x.description, "Description")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.description, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-warning btn-sm" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Unit/Delete.cshtml
@model Marcomm.ViewModel.UnitViewModel
@{
    ViewBag.Title = "Delete";
}

<div class="box box-primary box-solid">
    <div class="box-header">
        <div class="box-title"><strong>Delete Unit</strong></div>
    </div>
    <div class="box-body">
        <table>
            <tr>
                <td>
                    @using (Html.BeginForm())
            {
                        @Html.HiddenFor(x => x.id)
                        @Html.HiddenFor(x => x.code)
                        <button class="btn btn-danger btn-sm">Hapus</button>
                    }
                </td>
                <td>@Html.ActionLink("Batal", "Index", null, new { @class = "btn btn-primary btn-sm" })</td>
                <td></td>
            </tr>
        </table>
    </div>
</div>

Marcomm.Web/Views/Unit/Details.cshtml
@model Marcomm.ViewModel.UnitViewModel
@{
    ViewBag.Title = "Details";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.id)
    <div class="box box-primary box-solid">
        <div class="box-header">
            <div class="box-title"><strong>Details Unit - @Model.name (@Model.code) </strong></div>
        </div>
        <div class="box-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.Label("*Unit Code")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = true })
                        @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.Label("*Unit Name")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.name, new { @class = "form-control", @readonly = true })
                        @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.LabelFor(x => x.description, "Description")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.description, new { @class = "form-control", @readonly = true })
                        @Html.ValidationMessageFor(x => x.description, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-warning btn-sm" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Marcomm.Web/Views/Unit/Edit.cshtml
@model Marcomm.ViewModel.UnitViewModel
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.id)
    <div class="box box-primary box-solid">
        <div class="box-header">
            <div class="box-title"><strong>Edit Unit - @Model.name (@Model.code) </strong></div>
        </div>
        <div class="box-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.Label("*Unit Code")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = true })
                        @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.Label("*Unit Name")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 control-label">
                        @Html.LabelFor(x => x.description, "Description")
                    </div>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.description, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-warning btn-sm" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Unit/Index.cshtml
@model IEnumerable<Marcomm.ViewModel.UnitViewModel>

<div class=" box box-primary box-solid">
    <div class="box-header">
        <div class="box-title">List Unit</div>
    </div>
    <div class="box-body">
        <ol class="breadcrumb">
            <li>Home</li>
            <li>Master</li>
            <li>Unit</li>
        </ol>
        <div id="alert-box">

        </div>
        <table class="table" id="list-Unit">
            <thead id="tb-input">
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><button class="btn btn-primary btn-sm col-sm-6" id="btn-add">Add</button></td>
                </tr>
                <tr id="tb-input">
                    @*@using (Html.BeginForm("Search", "Unit", FormMethod.Post, new { @id = "form-search" }))
                        {*@
                    <td width="250px" colspan="2">
                        @Html.TextBox("code", "", new
                   {
                       @class = "form-control col-sm-8",
                       @placeholder = "-Select Unit Code -",
                       @data = 1,
                       @id = "col1-filter"
                   })
                    </td>
                    <td width="250px">
                        @Html.TextBox("name", "", new
                   {
                       @class = "form-control col-sm-8",
                       @placeholder = "- Select Unit Name -",
                       @data = 2,
                       @id = "col2-filter"
                   })
                    </td>
                    <td>
                        <div class="input-group">
                            @Html.TextBox("createdDate", "", new { @class = "form-control date datepicker", @placeholder = "- Date -", @data = 3, @id = "col3-filter" })
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </td>
                    <td>
                        @Html.TextBox("createdBy", "", new { @class = "form-control", @placeholder = "- Created By -", @data = 4, @id = "col4-filter" })
                    </td>
                    <td width="200px"><button class="btn btn-warning btn-sm col-sm-6" id="btn-search">Search</button></td>
                    @*}*@
                </tr>
                <tr>
                    <th>No.</th>
                    <th>Unit Code</th>
                    <th>Unit Name</th>
                    <th>Created Date</th>
                    <th>Created By</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="list-data">
                @Html.Partial("List", Model)
            </tbody>
        </table>
        <div id="alert-box">

        </div>
    </div>
</div>
<div class="modal fade" id="modal-input">
    <div class="modal-dialog" Unit="dialog">
        <div class="modal-content">
            @*<div class="modal-header">
                    <h3 id="modal-title">Modal Header</h3>
                </div>*@
            <div class="modal-body" id="modal-body">

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function loadData() {
            $.ajax({
                url: "@Url.Action("List", "Unit")",
                type: "get",
                dataType: "html",
                success: function (hasil) {
                    $("#list-data").html(hasil);
                }
            });
        }
        //table
        $(document).ready(function () {
            $("#list-Unit").DataTable({
                "sDom": "tip",
                ordering: false
            });
        });

        $("#btn-search").click(function () {
            $("#tb-input .form-control").each(function (i) {
                filterColumn($(this).attr("data"));
            });
        });

        function filterColumn(i) {
            $("#list-Unit").DataTable().column(i).search(
                $("#col" + i + "-filter").val()
                ).draw();

        }

        //ADD Get, menampilkan Add di dalam modal-input
        $("#btn-add").click(function () {
            $.ajax({
                url: "@Url.Action("Add", "Unit")",
                type: "get",
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Add Unit");
                    $("#modal-input").modal('show');
                }
            });
        });

        //Untuk submit data melalui form Add, action Add
        $("#modal-input").on("submit", "form", function () {
            var dataURL = $(this).attr("action");
            var dataMethod = $(this).attr("method");
            var dataItem = $(this).serialize();
            $.ajax({
                url: dataURL,
                type: dataMethod,
                data: dataItem,
                dataType: "json",
                success: function (hasil) {
                    if (hasil.success==true) {
                        if (hasil.from == "add") {
                            $("#modal-input").modal('hide');
                            loadData();
                            var response = "<div class='callout callout-info' id='alert'><strong>Data Saved!</strong> New Unit has been add with Unit code <strong>" + hasil.code + "</strong></div>";
                            $("#alert-box").append(response);
                            $("#alert-box").find("#alert").fadeOut(7000, function () {
                                $("#alert-box").find("#alert").remove();
                            });
                        } else if (hasil.from == "edit") {
                            $("#modal-input").modal('hide');
                            loadData();
                            var response = "<div class='callout callout-info' id='alert'><strong>Data Updated!</strong> Data Unit with Unit code <strong>" + hasil.code + "</strong> has been updated</div>";
                            $("#alert-box").append(response);
                            $("#alert-box").find("#alert").fadeOut(7000, function () {
                                $("#alert-box").find("#alert").remove();
                            });
                        } else if (hasil.from == "delete") {
                            $("#modal-input").modal('hide');
                            loadData();
                            var response = "<div class='callout callout-danger' id='alert'><strong>Data Deleted!</strong> Data Unit with Unit code <strong>"+hasil.code+"</strong> has been deleted</div>";
                            $("#alert-box").append(response);
                            $("#alert-box").find("#alert").fadeOut(7000, function () {
                                $("#alert-box").find("#alert").remove();
                            });
                        }
                    } else if (hasil.success == "ada") {
                        var response = "Data with name " + hasil.name + " is already exist!";
                        alert(response);
                    } else if (hasil.success == "kembali") {
                        $("#modal-input").modal('hide');
                        loadData();
                        var response = "<div class='callout callout-info' id='alert'><strong>Data Actived!</strong> Data Unit with Unit name <strong>" + hasil.name + "</strong> has been actived</div>";
                        $("#alert-box").append(response);
                        $("#alert-box").find("#alert").fadeOut(7000, function () {
                            $("#alert-box").find("#alert").remove();
                        });
                    }
                    else {
                        $("#modal-body").html(hasil);
                    }
                }
            });
            return false;
        });

        //Searchform-search
        $("#form-search").submit(function () {
            //alert("Tes");
            var dataURL = $(this).attr("action");
            var dataMethod = $(this).attr("method");
            var dataItem = $(this).serialize();
            $.ajax({
                url: dataUrl,
                type: dataMethod,
                dataType: "html",
                data: dataItem,
                success: function (hasil) {
                    $("#list-data").html(hasil);
                    return false;
                }
            });
            return false;
        });


        //Edit data
        $("#list-data").on("click", "#btn-edit", function () {
            var dataId = $(this).val();
            $.ajax({
                url: "@Url.Action("Edit", "Unit")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    //$("#modal-title").html("Edit Data Unit");
                    $("#modal-input").modal('show');
                }
            });
        });

        //Hapus data
        $("#list-data").on("click", "#btn-delete", function () {
            var dataId = $(this).val();
            $.ajax({
                url: "@Url.Action("Delete", "Unit")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Delete Data ?");
                    $("#modal-input").modal('show');
                }
            });
        });

        //data detail
        $("#list-data").on("click", "#btn-view", function () {
            var dataId = $(this).val();
            $.ajax({
                url: "@Url.Action("Details", "Unit")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Data Detail");
                    $("#modal-input").modal('show');
                }
            });
        });


        //datepicker
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            orientation: 'left-bottom'
        });

        //focusout
        //$("#modal-input").find("#name").on("click", function () {
        //    alert("Salah");
        //});

        //function coba() {
        //    var cek = $("#modal-input").find("#name").val();
        //    alert(cek);
        //};

    </script>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Unit/List.cshtml
@model IEnumerable<Marcomm.ViewModel.UnitViewModel>
@{
    ViewBag.Title = "List";
}

@{
    int i = 0;
}
@foreach (var item in Model)
{
    i = i + 1;
    string strdate = item.createdDate.HasValue ? item.createdDate.Value.ToString("dd/MM/yyyy") : string.Empty;
    <tr>
        <td>@i.</td>
        <td>@item.code</td>
        <td>@item.name</td>
        <td>@strdate</td>
        <td>@item.createdBy</td>
        <td>
            <button class="btn btn-success btn-xs" id="btn-view" value="@item.id">
                <i class="glyphicon glyphicon-eye-open"></i>
            </button>

            <button class="btn btn-warning btn-xs" id="btn-edit" value="@item.id">
                <i class="glyphicon glyphicon-pencil"></i>
            </button>

            <button class="btn btn-danger btn-xs" id="btn-delete" value="@item.id">
                <i class="glyphicon glyphicon-trash"></i>
            </button>
        </td>
    </tr>
}