Marcomm.Web/Controllers/SouvenirController.cs
using Marcomm.DAL;
using Marcomm.ViewModel;
using Marcommm.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marcomm.Web.Controllers
{
    public class SouvenirController : Controller
    {
        // GET: Souvenir
        public ActionResult Index()
        {
            ViewBag.ListUnit = new SelectList(UnitDAL.Get(), "name", "name");
            return View(SouvenirDAL.Get());
        }

        public ActionResult List()
        {
            return PartialView(SouvenirDAL.Get());
        }

        public ActionResult Add()
        {
            var data = new SouvenirViewModel();
            data.code = SouvenirDAL.KodeAuto();
            ViewBag.ListUnit = new SelectList(UnitDAL.Get(), "id", "name");
            return PartialView(data);
        }

        [HttpPost]
        public ActionResult Add(SouvenirViewModel model)
        {
            ViewBag.ListUnit = new SelectList(UnitDAL.Get(), "id", "name");
            if (ModelState.IsValid)
            {
                if (SouvenirDAL.Insert(model))
                {
                    var result = new { success = true, message = "Data Berhasil Tersimpan" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { success = false, message = "Data Gagal Tersimpan" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.ListUnit = new SelectList(UnitDAL.Get(), "id", "name");
            return PartialView(SouvenirDAL.Get(id));
        }

        [HttpPost]
        public ActionResult Edit(SouvenirViewModel model)
        {
            ViewBag.ListUnit = new SelectList(UnitDAL.Get(), "id", "name");
            //if (ModelState.IsValid)
            {
                if (SouvenirDAL.Update(model))
                {
                    var result = new { @success = true, message = "Success" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new { success = false, message = "Failed" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView(model);
        }

        public ActionResult Delete(int id)
        {
            return PartialView(SouvenirDAL.Get(id));
        }

        [HttpPost]
        public ActionResult Delete(SouvenirViewModel model)
        {
            if (SouvenirDAL.Delete(model))
            {
                var result = new { success = true, message = "Success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = new { success = false, message = "Failed" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView();
        }

        public ActionResult Detail(int id)
        {
            return PartialView(SouvenirDAL.Get(id));
        }

        public JsonResult panggil(int id)
        {
            var result = new
            {
                data = CompanyDAL.Get(id),
                success = true
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Marcomm.Web/Views/Souvenir/Add.cshtml
@model Marcomm.ViewModel.SouvenirViewModel
@{
    ViewBag.Title = "Add";
}

@using (Html.BeginForm("Add", "Souvenir", FormMethod.Post, new { @id = "form" }))
{
    @Html.HiddenFor(x => x.isDelete, new { Value = false })
    @Html.HiddenFor(x => x.createdBy, new { Value = "Admin" })
    @*@Html.HiddenFor(x => x.quantity, new { Value = "100" })*@
    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.code, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })

                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.mUnitName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.mUnitId, (IEnumerable<SelectListItem>)ViewBag.ListUnit, "- Select Unit Name -", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.mUnitId, null, new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.description, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
                <a id="btn-cancel" class="btn btn-warning btn-sm">Cancel</a>
            </div>
        </div>

    </div>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Souvenir/Delete.cshtml
@model Marcomm.ViewModel.SouvenirViewModel
@{
    ViewBag.Title = "Delete";
}
<table>
    <tr>
        <td width="3">
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(x => x.id)
                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            }
        </td>
        <td>
            <button id="btn-cancel" class="btn btn-warning btn-sm">Cancel</button>
        </td>
    </tr>
</table>

Marcomm.Web/Views/Souvenir/Detail.cshtml
@model Marcomm.ViewModel.SouvenirViewModel
@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.isDelete, new { Value = false })
    @Html.HiddenFor(x => x.createdBy, new { Value = "Admin" })
    @Html.HiddenFor(x => x.id)
    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.code, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })

                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.name, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.mUnitName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.unitName, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.unitName, null, new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.description, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.description, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <a id="btn-cancel" class="btn btn-warning btn-sm">Close</a>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Souvenir/Edit.cshtml
@model Marcomm.ViewModel.SouvenirViewModel
@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.isDelete, new { Value = false })
    @Html.HiddenFor(x => x.createdBy, new { Value = "Admin" })
    @Html.HiddenFor(x => x.id)
    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.code, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.code, new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.code, null, new { @class = "text-danger" })

                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.name, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.mUnitName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.mUnitId, (IEnumerable<SelectListItem>)ViewBag.ListUnit, "- Select Unit Name -", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.mUnitId, null, new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.description, null, new { @class = "text-danger" })

                </div>
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
                <a id="btn-cancel" class="btn btn-warning btn-sm">Cancel</a>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

Marcomm.Web/Views/Souvenir/Index.cshtml
@model IEnumerable<Marcomm.ViewModel.SouvenirViewModel>
@{
    ViewBag.Title = "Index";
}

<div class="box box-primary box-solid">
    <div class="box-header">
        <div class="box-title">List Souvenir</div>
    </div>
</div>

<div class="box-body">
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Master</li>
        <li>List Souvenir</li>
    </ol>
</div>

<table class="table table-bordered table-responsive table-striped" id="list-role">
    <thead id="tb-input">
        <tr>
            <td colspan="5"></td>
            <td>
                <button type="button" class="btn btn-primary col-md-5" id="btn-add">Add</button>
            </td>
        </tr>

        <tr>
            <td></td>
            <td>@Html.TextBox("code", "", new { @class = "form-control column-filter", @id = "col1_filter", @data = "1", @placeholder = "Souvenir Code" })</td>
            <td>@Html.TextBox("name", "", new { @class = "form-control column-filter", @id = "col2_filter", @data = "2", @placeholder = "Souvenir Name" })</td>
            <td>@Html.DropDownList("mUnitId", (IEnumerable<SelectListItem>)ViewBag.ListUnit, "- Select Unit Name -", new { @class = "form-control column-filter", @id = "col3_filter", @data = "3" })</td>
            <td>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" class="datepicker form-control column_filter" id="col4_filter" data="4" placeholder="Created" />
                </div>
            </td>
            <td>@Html.TextBox("createdBy", "", new { @class = "form-control column-filter", @id = "col5_filter", @data = "5", @placeholder = "Created By" })</td>
            <td>
                <button class="btn btn-warning" id="btn-src">Search</button>
            </td>
        </tr>
        <tr>
            <th>No.</th>
            <th>@Html.DisplayNameFor(x => x.code)</th>
            <th>@Html.DisplayNameFor(x => x.name)</th>
            <th>@Html.DisplayNameFor(x => x.mUnitName)</th>
            <th>@Html.DisplayNameFor(x => x.createdDate)</th>
            <th>@Html.DisplayNameFor(x => x.createdBy)</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody id="list-data">
        @Html.Partial("List", Model)
    </tbody>
</table>


<div class="modal fade" id="modal-input">
    <div class="modal-dialog" role="dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">Modal Header</h3>
            </div>
            <div class="modal-body" id="modal-body">

            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        function loadData() {
            $.ajax({
                url: "@Url.Action("List","Souvenir")",
                type: "get",
                dataType: "html",
                success: function (x) {
                    $("#list-data").html(x);
                }
            });
        };

        $(document).ready(function () {
            $("#list-role").DataTable({
                'sDom': 'tip',
                ordering: false
            });
            $("#tb-input").find(".column_filter").on("keyup click", function () {
                filtercolumn($(this).attr("data-column"));
            });
        });

        function filtercolumn(i) {
            $("#list-role").DataTable().column(i).search(
                $("#col" + i + "_filter").val()
                ).draw();
        };

        $("#btn-src").click(function () {
            $("#tb-input .form-control").each(function () {
                filtercolumn($(this).attr('data'));
            });
        });

        $("#tb-input").find(".datepicker").datepicker({
            Format: "MM/dd/yyyy",
            autoclose: true
        });
        //ADD Get, menampilkan Add di dalam modal-input
        $("#btn-add").click(function () {
            $.ajax({
                url: "@Url.Action("Add", "Souvenir")",
                type: "get",
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Add Souvenir");
                    $("#modal-input").modal('show');
                }
            });
        });

        //untuk cancel
        $("#modal-input").on("click", "#btn-cancel", function () {
            $("#modal-input").modal('hide');
        });

        //Untuk submit data melalui form Add, action Add
        $("#modal-input").on("submit", "form", function () {
            var dataURL = $(this).attr("action");
            var dataMethod = $(this).attr("method");
            var dataItem = $(this).serialize();

            $.ajax({
                url: dataURL,
                type: dataMethod,
                data: dataItem,
                dataType: "json",
                success: function (hasil) {
                    if (hasil.success) {
                        loadData();
                        $("#modal-input").modal('hide');
                    } else {
                        $("#modal-body").html(hasil);
                    }
                }
            });
            return false;
        });

        //Edit data
        $("#list-data").on("click", "#btn-edit", function () {
            var dataId = $(this).val();
            $.ajax({
                url: "@Url.Action("Edit", "Souvenir")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Edit Souvenir");
                    $("#modal-input").modal('show');
                }
            });
        });

        //Hapus data
        $("#list-data").on("click", "#btn-delete", function () {
            var dataId = $(this).val();

            $.ajax({
                url: "@Url.Action("Delete", "Souvenir")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("Delete Data?");
                    $("#modal-input").modal('show');
                }
            });
        });

        //data detail
        $("#list-data").on("click", "#btn-view", function () {
            var dataId = $(this).val();
            $.ajax({
                url: "@Url.Action("Detail", "Souvenir")",
                type: "get",
                data: { id: dataId },
                dataType: "html",
                success: function (hasil) {
                    $("#modal-body").html(hasil);
                    $("#modal-title").html("View Souvenir");
                    $("#modal-input").modal('show');
                }
            });
        });
    </script>
}

Marcomm.Web/Views/Souvenir/List.cshtml
@model IEnumerable<Marcomm.ViewModel.SouvenirViewModel>
@{
    ViewBag.Title = "List";
    int i = 0;
}
@foreach (var item in Model)
{
    i += 1;
    <tr>
        <td>@i</td>
        <td>@item.code</td>
        <td>@item.name</td>
        <td>@item.unitName</td>
        <td>@item.createdDate</td>
        <td>@item.createdBy</td>
        <td>
            <button class="btn btn-success btn-xs" id="btn-view" value="@item.id">
                <i class="glyphicon glyphicon-eye-open"></i>
            </button>

            <button class="btn btn-warning btn-xs" id="btn-edit" value="@item.id">
                <i class="glyphicon glyphicon-pencil"></i>
            </button>

            <button class="btn btn-danger btn-xs" id="btn-delete" value="@item.id">
                <i class="glyphicon glyphicon-trash"></i>
            </button>
        </td>
    </tr>
}